// This file will be generated by: supabase gen types typescript --local
// For now, providing a basic structure that matches the schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          logo_url: string | null
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          logo_url?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          logo_url?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          org_id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          role: 'admin' | 'manager' | 'user' | 'client' | 'client_no_access'
          is_active: boolean
          metadata: Json
          allowed_org_ids: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          org_id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          role: 'admin' | 'manager' | 'user' | 'client' | 'client_no_access'
          is_active?: boolean
          metadata?: Json
          allowed_org_ids?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          role?: 'admin' | 'manager' | 'user' | 'client' | 'client_no_access'
          is_active?: boolean
          metadata?: Json
          allowed_org_ids?: string[]
          created_at?: string
          updated_at?: string
        }
      }
      files: {
        Row: {
          id: string
          org_id: string
          name: string
          size: number
          mime_type: string
          storage_path: string
          folder_path: string
          uploaded_by: string
          version: number
          parent_file_id: string | null
          description: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          name: string
          size: number
          mime_type: string
          storage_path: string
          folder_path?: string
          uploaded_by: string
          version?: number
          parent_file_id?: string | null
          description?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          name?: string
          size?: number
          mime_type?: string
          storage_path?: string
          folder_path?: string
          uploaded_by?: string
          version?: number
          parent_file_id?: string | null
          description?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      file_permissions: {
        Row: {
          id: string
          file_id: string
          user_id: string | null
          role: string | null
          permission: 'view' | 'edit' | 'delete'
          created_at: string
        }
        Insert: {
          id?: string
          file_id: string
          user_id?: string | null
          role?: string | null
          permission: 'view' | 'edit' | 'delete'
          created_at?: string
        }
        Update: {
          id?: string
          file_id?: string
          user_id?: string | null
          role?: string | null
          permission?: 'view' | 'edit' | 'delete'
          created_at?: string
        }
      }
      user_organizations: {
        Row: {
          id: string
          user_id: string
          org_id: string
          is_primary: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          org_id: string
          is_primary?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          org_id?: string
          is_primary?: boolean
          created_at?: string
        }
      }
      tasks: {
        Row: {
          id: string
          org_id: string
          title: string
          description: string | null
          status: 'pending' | 'in_progress' | 'completed' | 'cancelled'
          priority: 'low' | 'medium' | 'high' | 'urgent'
          assigned_to: string | null
          created_by: string
          due_date: string | null
          completed_at: string | null
          is_internal: boolean
          is_recurring: boolean
          recurrence_rule: Json | null
          parent_task_id: string | null
          next_occurrence_at: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          org_id: string
          title: string
          description?: string | null
          status?: 'pending' | 'in_progress' | 'completed' | 'cancelled'
          is_internal?: boolean
          is_recurring?: boolean
          recurrence_rule?: Json | null
          parent_task_id?: string | null
          next_occurrence_at?: string | null
          priority?: 'low' | 'medium' | 'high' | 'urgent'
          assigned_to?: string | null
          created_by: string
          due_date?: string | null
          completed_at?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          title?: string
          description?: string | null
          status?: 'pending' | 'in_progress' | 'completed' | 'cancelled'
          priority?: 'low' | 'medium' | 'high' | 'urgent'
          assigned_to?: string | null
          created_by?: string
          due_date?: string | null
          completed_at?: string | null
          is_internal?: boolean
          is_recurring?: boolean
          recurrence_rule?: Json | null
          parent_task_id?: string | null
          next_occurrence_at?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      task_attachments: {
        Row: {
          id: string
          task_id: string
          file_id: string
          attached_by: string
          created_at: string
        }
        Insert: {
          id?: string
          task_id: string
          file_id: string
          attached_by: string
          created_at?: string
        }
        Update: {
          id?: string
          task_id?: string
          file_id?: string
          attached_by?: string
          created_at?: string
        }
      }
      activity_log: {
        Row: {
          id: string
          org_id: string
          user_id: string | null
          action: string
          entity_type: string
          entity_id: string
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          org_id: string
          user_id?: string | null
          action: string
          entity_type: string
          entity_id: string
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: string
          org_id?: string
          user_id?: string | null
          action?: string
          entity_type?: string
          entity_id?: string
          metadata?: Json
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          title: string
          message: string
          type: 'info' | 'success' | 'warning' | 'error'
          entity_type: string | null
          entity_id: string | null
          read: boolean
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          message: string
          type: 'info' | 'success' | 'warning' | 'error'
          entity_type?: string | null
          entity_id?: string | null
          read?: boolean
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          message?: string
          type?: 'info' | 'success' | 'warning' | 'error'
          entity_type?: string | null
          entity_id?: string | null
          read?: boolean
          metadata?: Json
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      user_org_id: {
        Args: Record<string, never>
        Returns: string
      }
      user_role: {
        Args: Record<string, never>
        Returns: string
      }
      get_user_org_ids: {
        Args: Record<string, never>
        Returns: string[]
      }
      is_team_member: {
        Args: Record<string, never>
        Returns: boolean
      }
      is_admin_or_manager: {
        Args: Record<string, never>
        Returns: boolean
      }
      can_access_org: {
        Args: { target_org_id: string }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
